### PR TITLE
Add init option to disable preloading

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Comment by bbannier** [comment]
@awelzel, this is the option you had asked me about. Getting it in was not very hard, but I still wonder whether this addresses your problem while still keeping things working.

The main issue I wonder about is that normal preloading on startup is done in parallel while doing this lazy would execute most requests sequentially when needed (and parallelizing _everything_ is pretty intrusive). On my machine preloading takes about 600ms (16 cores) and with that I get a hover in ~70ms; if I disable preloading startup is very fast (60ms), but completing took 10,000 ms.

I also wonder about other requests a client might send implicitly. I checked semantic highlighting which is still fast since it currently does not involve resolved information (this might change). Inlay hints OTOH could take a long time to show up with this since they would trigger slow, sequential computations of needed information now.

If this looks useful to you I can still merge it since it is not too intrusive.

**Comment by bbannier** [comment]
Closing since this seems not needed anymore.

**Comment by awelzel** [comment]
> @awelzel, this is the option you had asked me about.

I'm not sure this is really what I was looking for.

I've just upgraded the language server and it loads really fast (might have had a rather old version) when my system is otherwise idle. Things end up differently 

I am reflecting. Maybe I'm more irritated by all cores being used by default. But I might just be too old school.

**Comment by bbannier** [comment]
Looking at [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) I see these config flags expose in vscode which seems strongly related to what you wanted.
Screenshot 2024-12-09 at 5 42 56 PM

As for the use of multiple cores, right now there is ad hoc parallelism in a few places, some via `tokio::spawn` on the server's runtime and some via `rayon`'s `par_iter`:
- preload on change of watch files: this is what you see on startup when system scripts are loaded, file reading and indexing are parallelized separately
- computation of inlay hints, separately for variables and parameters
- result computation for FindReferences
- getting file listings in the different system dirs via `zeek-config --[script|plugin|site]-dir`
- some parallelized filtering of bigger collections, e.g., for partitioning or conversion 

Most of these are fast enough that you probably did not notice.

Since many are run on the server's runtime (where we want to be able to have more than one request in flight at a time), or with default parallelism in rayon, limiting concurrently consistently would involve moving all that code to some common infrastructure. Since this is likely much more work than the change I put up in this PR, it would be great if you could check whether this is still an issue for you (you mentioned that this now ran much faster than before for you). I'd also still argue that most users would consider completions taking 5s a higher priority issue than 2s of high CPU load indexing worst case.

**Pull request closed without merging**
